spring:
  application:
    name: weather-alert-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: alert-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.json.trusted.packages: "*"
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
    listener:
      ack-mode: record

kafka:
  alert:
    topic:
      hot_weather: alert-hot-weather
