spring:
  application:
    name: weather-analytics-service
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      transaction-id-prefix: kafka-tx-id-
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true
        use.latest.version: true
    consumer:
      group-id: analytics-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
    listener:
      ack-mode: record
  data:
    mongodb:
      database: weather-analytics
      auto-index-creation: true

kafka:
  header:
    source: 'weather-analytics-service'
    version: '1.0'
  data:
    topic:
      raw: data-raw
  notification:
    topic:
      hot_weather: notification-hot-weather
      ignore: notification-ignore
  alert:
    topic:
      hot_weather: alert-hot-weather

weather:
  heat-index-alert: 40
  dew-point-alert: 25
  temp-deviation-alert: 5
  rules:
    - region: "Bangkok"
      temperatureThreshold: 36
      humidityThreshold: 30
    - region: "Hanoi"
      temperatureThreshold: 34
      humidityThreshold: 25
    - region: "Tokyo"
      temperatureThreshold: 37
      humidityThreshold: 40
      pressureThreshold: 900

outbox:
  processor:
    cron: "0 */5 * * * *"
