spring:
  application:
    name: weather-analytics-service
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true
        use.latest.version: true
    consumer:
      group-id: analytics-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
    listener:
      ack-mode: record
  data:
    mongodb:
      database: weather-analytics
      host: localhost
      port: 27017
      username: openweather
      password: openweather
      authentication-database: admin

kafka:
  internal:
      topic:
        hot: internal-hot-weather
  data:
    topic:
      raw: data-raw
  notification:
    topic:
      hot_weather: notification-hot-weather
