spring:
  application:
    name: weather-analytics-service
  kafka:
    bootstrap-servers: localhost:9094
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    producer:
      transaction-id-prefix: kafka-tx-id-
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
        auto.register.schemas: true
        use.latest.version: true
    consumer:
      group-id: analytics-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    listener:
      ack-mode: record
    streams:
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value:
            serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
  data:
    mongodb:
      database: weather-analytics
      auto-index-creation: true

kafka:
  header:
    source: 'weather-analytics-service'
    version: '1.0'
  data:
    topic:
      raw: data-raw
  notification:
    topic:
      hot_weather: notification-hot-weather
      ignore: notification-ignore
  alert:
    topic:
      hot_weather: alert-hot-weather
  weather:
    topic:
      ignored: weather-ignored
      trends: weather-trends
  analytics:
    topic:
      invalid: analytics-invalid
    sliding-window-duration: 10m

weather:
  heat-index-alert: 40
  dew-point-alert: 25
  temp-deviation-alert: 5

outbox:
  processor:
    cron: "0 */5 * * * *"
analytics:
  avg_temperature_trends:
    minute_window: 10
    cron:
      job: "0 */10 * * * *"
