{
  "type": "record",
  "name": "HotWeatherAlertEvent",
  "namespace": "org.sideprj.openweathermicroservices.avro",
  "fields": [
    {
      "name": "alertId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "city",
      "type": "string"
    },
    {
      "name": "country",
      "type": "string"
    },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "temperature",
      "type": "double"
    },
    {
      "name": "humidity",
      "type": "double"
    },
    {
      "name": "severity",
      "type": {
        "type": "enum",
        "symbols": [
          "MEDIUM",
          "HIGH"
        ],
        "name": "SeverityEnum"
      }
    },
    {
      "name": "reasons",
      "type": {
        "type": "array",
        "default": [],
        "items": {
          "type": "enum",
          "symbols": [
            "HOT",
            "DRY"
          ],
          "name": "ReasonEnum"
        }
      }
    }
  ]
}
