spring:
  application:
    name: weather-recommendation-service
  ai:
    openai:
      base-url: https://ollama.com
      chat:
        options:
          model: gpt-oss:20b-cloud
  data:
    mongodb:
      database: weather-recommendation